# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pictate"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adnan Abdulhussein"]
  s.date = "2012-04-25"
  s.description = "Pointless command line tool that attempts to describe the image you give it by automating a google search by image."
  s.email = "adnan@prydoni.us"
  s.executables = ["pictate"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/pictate",
    "ext/.gitignore",
    "lib/pictate.rb",
    "pictate.gemspec",
    "test/helper.rb",
    "test/test_pictate.rb"
  ]
  s.homepage = "http://github.com/Prydonius/pictate"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Attempts to describe a picture you give it."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<selenium-webdriver>, ["~> 2.20"])
      s.add_runtime_dependency(%q<choice>, ["~> 0.1.6"])
      s.add_runtime_dependency(%q<spinning_cursor>, ["~> 0.1.0.rc1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<selenium-webdriver>, ["~> 2.20"])
      s.add_dependency(%q<choice>, ["~> 0.1.6"])
      s.add_dependency(%q<spinning_cursor>, ["~> 0.1.0.rc1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<selenium-webdriver>, ["~> 2.20"])
    s.add_dependency(%q<choice>, ["~> 0.1.6"])
    s.add_dependency(%q<spinning_cursor>, ["~> 0.1.0.rc1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

